// グローバルCSSの読み込み（全ページに共通して適用されるスタイル）
import '../styles/globals.css';

// HTMLの <head> 内に入るメタデータ（SEOやタブタイトルなどに使用される）
export const metadata = {
  title: 'Next.js',                      // ブラウザのタブタイトルなどに反映される
  description: 'Generated by Next.js',   // ページ説明（SEOなどに使用）
}

// ルートレイアウトコンポーネント
// App Router において、全ページで共通して使われるレイアウト（ナビゲーションやフッターなどを含めてもOK）
export default function RootLayout({
  children, // 各ページ（page.tsx）の内容がここに差し込まれる
}: {
  children: React.ReactNode // Reactノード型（任意のJSX構造）
}) {
  return (
    // HTML文書のルート要素
    <html lang="en">
      {/* 実際のページの描画部分（ここにすべてのページコンポーネントが挿入される） */}
      <body>{children}</body>
    </html>
  )
}
